export const categories = [
  {
    id: 1,
    type: "repair",
    name: "Ремонт, монтаж, отделка",
    subcategories: [
      {
        id: 101,
        name: "Услуги электриков",
        parentType: "repair",
        subType: "electrician",
      },
      {
        id: 102,
        name: "Услуги маляров и штукатуров",
        parentType: "repair",
        subType: "painter_plasterer",
      },
      {
        id: 103,
        name: "Услуги сантехников",
        parentType: "repair",
        subType: "plumber",
      },
      {
        id: 104,
        name: "Укладка плитки",
        parentType: "repair",
        subType: "tile_laying",
      },
      {
        id: 105,
        name: "Ремонт квартир и домов",
        parentType: "repair",
        subType: "apartment_repair",
      },
      {
        id: 106,
        name: "Демонтажные работы",
        parentType: "repair",
        subType: "dismantling",
      },
      {
        id: 107,
        name: "Монтаж натяжных потолков",
        parentType: "repair",
        subType: "ceiling_installation",
      },
      {
        id: 108,
        name: "Утепление фасадов",
        parentType: "repair",
        subType: "facade_insulation",
      },
      {
        id: 109,
        name: "Ремонт полов",
        parentType: "repair",
        subType: "floor_repair",
      },
      {
        id: 110,
        name: "Сварочные работы",
        parentType: "repair",
        subType: "welding",
      },
    ],
  },
  {
    id: 2,
    type: "home_help",
    name: "Помощь по дому",
    subcategories: [
      {
        id: 201,
        name: "Уборка квартир и домов",
        parentType: "home_help",
        subType: "cleaning",
      },
      {
        id: 202,
        name: "Домработницы",
        parentType: "home_help",
        subType: "housekeeper",
      },
      {
        id: 203,
        name: "Чистка ковров и мебели",
        parentType: "home_help",
        subType: "carpet_cleaning",
      },
      {
        id: 204,
        name: "Глажка белья",
        parentType: "home_help",
        subType: "ironing",
      },
      {
        id: 205,
        name: "Мытьё окон",
        parentType: "home_help",
        subType: "window_cleaning",
      },
      {
        id: 206,
        name: "Генеральная уборка",
        parentType: "home_help",
        subType: "deep_cleaning",
      },
      {
        id: 207,
        name: "Вынос мусора",
        parentType: "home_help",
        subType: "garbage_disposal",
      },
      {
        id: 208,
        name: "Уход за садом и огородом",
        parentType: "home_help",
        subType: "garden_care",
      },
      {
        id: 209,
        name: "Услуги няни",
        parentType: "home_help",
        subType: "nanny",
      },
      {
        id: 210,
        name: "Услуги сиделки",
        parentType: "home_help",
        subType: "caregiver",
      },
    ],
  },
  {
    id: 3,
    type: "construction",
    name: "Строительство",
    subcategories: [
      {
        id: 301,
        name: "Строительство домов под ключ",
        parentType: "construction",
        subType: "house_building",
      },
      {
        id: 302,
        name: "Фундаментные работы",
        parentType: "construction",
        subType: "foundation",
      },
      {
        id: 303,
        name: "Кровельные работы",
        parentType: "construction",
        subType: "roofing",
      },
      {
        id: 304,
        name: "Монтаж вентиляции",
        parentType: "construction",
        subType: "ventilation",
      },
      {
        id: 305,
        name: "Укладка брусчатки",
        parentType: "construction",
        subType: "paving",
      },
      {
        id: 306,
        name: "Строительство заборов",
        parentType: "construction",
        subType: "fence_building",
      },
      {
        id: 307,
        name: "Ландшафтный дизайн",
        parentType: "construction",
        subType: "landscape_design",
      },
      {
        id: 308,
        name: "Монтаж лестниц",
        parentType: "construction",
        subType: "stair_installation",
      },
      {
        id: 309,
        name: "Кладка кирпича",
        parentType: "construction",
        subType: "bricklaying",
      },
      {
        id: 310,
        name: "Гипсокартонные работы",
        parentType: "construction",
        subType: "drywall",
      },
    ],
  },
  {
    id: 1,
    type: "repair",
    name: "Ремонт, монтаж, отделка",
    subcategories: [
      {
        id: 101,
        name: "Услуги электриков",
        parentType: "repair",
        subType: "electrician",
      },
      {
        id: 102,
        name: "Услуги маляров и штукатуров",
        parentType: "repair",
        subType: "painter_plasterer",
      },
      {
        id: 103,
        name: "Услуги сантехников",
        parentType: "repair",
        subType: "plumber",
      },
      {
        id: 104,
        name: "Укладка плитки",
        parentType: "repair",
        subType: "tile_laying",
      },
      {
        id: 105,
        name: "Ремонт квартир и домов",
        parentType: "repair",
        subType: "apartment_repair",
      },
      {
        id: 106,
        name: "Демонтажные работы",
        parentType: "repair",
        subType: "dismantling",
      },
      {
        id: 107,
        name: "Монтаж натяжных потолков",
        parentType: "repair",
        subType: "ceiling_installation",
      },
      {
        id: 108,
        name: "Утепление фасадов",
        parentType: "repair",
        subType: "facade_insulation",
      },
      {
        id: 109,
        name: "Ремонт полов",
        parentType: "repair",
        subType: "floor_repair",
      },
      {
        id: 110,
        name: "Сварочные работы",
        parentType: "repair",
        subType: "welding",
      },
    ],
  },
  {
    id: 2,
    type: "home_help",
    name: "Помощь по дому",
    subcategories: [
      {
        id: 201,
        name: "Уборка квартир и домов",
        parentType: "home_help",
        subType: "cleaning",
      },
      {
        id: 202,
        name: "Домработницы",
        parentType: "home_help",
        subType: "housekeeper",
      },
      {
        id: 203,
        name: "Чистка ковров и мебели",
        parentType: "home_help",
        subType: "carpet_cleaning",
      },
      {
        id: 204,
        name: "Глажка белья",
        parentType: "home_help",
        subType: "ironing",
      },
      {
        id: 205,
        name: "Мытьё окон",
        parentType: "home_help",
        subType: "window_cleaning",
      },
      {
        id: 206,
        name: "Генеральная уборка",
        parentType: "home_help",
        subType: "deep_cleaning",
      },
      {
        id: 207,
        name: "Вынос мусора",
        parentType: "home_help",
        subType: "garbage_disposal",
      },
      {
        id: 208,
        name: "Уход за садом и огородом",
        parentType: "home_help",
        subType: "garden_care",
      },
      {
        id: 209,
        name: "Услуги няни",
        parentType: "home_help",
        subType: "nanny",
      },
      {
        id: 210,
        name: "Услуги сиделки",
        parentType: "home_help",
        subType: "caregiver",
      },
    ],
  },
  {
    id: 3,
    type: "construction",
    name: "Строительство",
    subcategories: [
      {
        id: 301,
        name: "Строительство домов под ключ",
        parentType: "construction",
        subType: "house_building",
      },
      {
        id: 302,
        name: "Фундаментные работы",
        parentType: "construction",
        subType: "foundation",
      },
      {
        id: 303,
        name: "Кровельные работы",
        parentType: "construction",
        subType: "roofing",
      },
      {
        id: 304,
        name: "Монтаж вентиляции",
        parentType: "construction",
        subType: "ventilation",
      },
      {
        id: 305,
        name: "Укладка брусчатки",
        parentType: "construction",
        subType: "paving",
      },
      {
        id: 306,
        name: "Строительство заборов",
        parentType: "construction",
        subType: "fence_building",
      },
      {
        id: 307,
        name: "Ландшафтный дизайн",
        parentType: "construction",
        subType: "landscape_design",
      },
      {
        id: 308,
        name: "Монтаж лестниц",
        parentType: "construction",
        subType: "stair_installation",
      },
      {
        id: 309,
        name: "Кладка кирпича",
        parentType: "construction",
        subType: "bricklaying",
      },
      {
        id: 310,
        name: "Гипсокартонные работы",
        parentType: "construction",
        subType: "drywall",
      },
    ],
  },
];
